### ISSUE TITLE
Sound stops playing almost instantly

### ISSUE THREAD

**Issue by illavaknus** [substack/baudio#22]
Hey! Great work with baudio! I have installed the latest version i.e. v1.2.1via npm on a macbook. My node version is v0.12.0. I am facing the same issue mentioned here : https://github.com/substack/baudio/issues/13,  where the sound plays for less than a second and stops. Any help would be appreciated! Here is the code : 

```
var baudio = require('baudio');
var b = baudio(function (t) {
  return Math.sin(2 * Math.PI * 1760 * t) * (t < 0.1);
});
b.play();
```

**Comment by substack** [comment]
@illavaknus The sound stops playing after 0.1 seconds because you have `(t < 0.1)`.

Change the code to:

``` js
var baudio = require('baudio');
var b = baudio(function (t) {
  return Math.sin(2 * Math.PI * 1760 * t);
});
b.play();
```

**Comment by illavaknus** [comment]
I am sorry - I pasted the incorrect code ( was trying out different things). 
```
var baudio = require('baudio');

var b = baudio(function (t) {
 // if(t>10) b.end();
  return Math.sin(2 * Math.PI * t * 440);
});

b.play();
```
I tried even the code you mentioned, but I face the same issue.

**Comment by illavaknus** [comment]
Interestingly when I debug the code (via node debug) and step through it, it plays the sound fine (including stopping after 10 seconds, when I uncomment the line in the code above). 
```javascript
var baudio = require('baudio');

var b = baudio(function (t) {
  if(t>10) b.end();
  return Math.sin(2 * Math.PI * t * 440);
});

b.play();
```

**Comment by illavaknus** [comment]
I tried debugging with node-debug and WebStorm IDE, and it intermittently runs fine while abruptly ending other times. Now, when I run from the terminal again, it runs fine intermittently (earlier it would stop almost immediately). I am guess the child process is being killed prematurely once in a while. Anyway, thank you for you help!

**Comment by camille-vanhoffelen** [comment]
I'm getting exactly the same issue. Found any solution to this?

**Comment by illavaknus** [comment]
I still face this issue on OSX, but the same code works fine on Windows.

Shashank Sunkavalli

**Comment by flimshaw** [comment]
I'm still seeing this in OS X as well, though it does occasionally work. Oddly, if I do console.log(b.play()) instead of just b.play(), it works fine every time.

```
var b = baudio(function (t) {
  return (Math.random() * 2. - 1.) || 1.0;
});

console.log(b.play());
```

Running node v8.4 on OS X 10.13.1
