### ISSUE TITLE
oscilloscope.jpg link is dead

### ISSUE THREAD

**Issue by zzmp** [substack/baudio#27]
I found a live copy in Google's cache of npmjs's version of baudio's readme:

![oscilloscope](https://user-images.githubusercontent.com/5403956/29890566-08db3aca-8d96-11e7-968d-591f341a5c4e.jpg)

@substack it seems your practice is to save it to substack.net/images/oscilloscope.jpg and serve it from there, so I'm opening an issue instead of a PR. I could no longer find it there.

**Comment by substack** [comment]
Works again. I am going to port my site over to neocities one of these days. My current thing runs out of memory all the time.
